### ISSUE TITLE
Remove usage of deprecated DefaultVersionSelectorScheme constructor

### ISSUE THREAD

**Issue by ljacomet** [nebula-plugins/nebula-gradle-interop#5]
The constructor `DefaultVersionSelectorScheme(VersionComparator versionComparator)` has been deprecated in Gradle and should be removed.
Its usage here prevents its removal as a number of Nebula plugins end up using it.

**Comment by rpalcolea** [comment]
Hi @ljacomet , thanks for the heads up

Just fixed this in https://github.com/nebula-plugins/nebula-gradle-interop/commit/79dc1715df87a65fe582d1389bb3db5c49cb9499. For now, just moving to `DefaultVersionSelectorScheme(VersionComparator versionComparator, VersionParser versionParser)` constructor.

Will rollout this change to other plugins soon
